"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const dotenv_1 = __importDefault(require("dotenv"));
dotenv_1.default.config();
const cors_1 = __importDefault(require("cors"));
const path_1 = __importDefault(require("path"));
const express_1 = __importDefault(require("express"));
const app = (0, express_1.default)();
app.use((0, cors_1.default)());
app.use(express_1.default.urlencoded({ extended: true }));
app.use(express_1.default.json());
app.use(express_1.default.static(path_1.default.resolve('./', 'client', 'build')));
app.use(express_1.default.static(path_1.default.resolve('./', 'client', 'public')));
const affiliate_networks_1 = require("./src/server/routes/affiliate-networks/affiliate-networks");
const campaigns_1 = require("./src/server/routes/campaigns/campaigns");
const clicks_1 = require("./src/server/routes/clicks/clicks");
const clk_1 = require("./src/server/routes/clk/clk");
const data_1 = require("./src/server/routes/data/data");
const flows_1 = require("./src/server/routes/flows/flows");
const landing_pages_1 = require("./src/server/routes/landing-pages/landing-pages");
const login_1 = require("./src/server/routes/login/login");
const logout_1 = require("./src/server/routes/logout/logout");
const offers_1 = require("./src/server/routes/offers/offers");
const postback_1 = require("./src/server/routes/postback/postback");
const t_1 = require("./src/server/routes/t/t");
const traffic_sources_1 = require("./src/server/routes/traffic-sources/traffic-sources");
app.use('/affiliate-networks', affiliate_networks_1.router);
app.use('/campaigns', campaigns_1.router);
app.use('/clicks', clicks_1.router);
app.use('/clk', clk_1.router);
app.use('/data', data_1.router);
app.use('/flows', flows_1.router);
app.use('/landing-pages', landing_pages_1.router);
app.use('/login', login_1.router);
app.use('/logout', logout_1.router);
app.use('/offers', offers_1.router);
app.use('/postback', postback_1.router);
app.use('/t', t_1.router);
app.use('/traffic-sources', traffic_sources_1.router);
app.get('*', (req, res) => {
    res.sendFile(path_1.default.resolve('./', 'client', 'build', 'index.html'));
});
const port = process.env.PORT || process.env.BACKEND_PORT || 3001;
app.listen(port, () => console.log(`Server running on port ${port}`));
